# Generated by Django 5.1.6 on 2025-03-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="sizes",
            field=models.CharField(
                blank=True,
                help_text="Enter sizes separated by commas (e.g., S, M, L, XL)",
                max_length=255,
                null=True,
            ),
        ),
    ]
