# Generated by Django 5.1.6 on 2025-04-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="prodcut", new_name="product",
        ),
    ]
